# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key
print(g_key)

AIzaSyC9rlhihsETnfda9XrAM-eY4BvLNjufWxM

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [6]:
data = pd.read_csv("../output_data/weather_df.csv", dtype="object", encoding = "utf-8")
data

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,pacific grove,36.62,-121.92,71.01,60,1,9.17,US,1596238050
1,1,hermanus,-34.42,19.23,44.01,95,1,5.75,ZA,1596238148
2,2,hobyo,5.35,48.53,77.16,75,1,28.16,SO,1596238149
3,3,pitimbu,-7.47,-34.81,73.4,94,20,5.82,BR,1596238149
4,4,hobart,-42.88,147.33,50.0,71,75,10.29,AU,1596237898
...,...,...,...,...,...,...,...,...,...,...
552,552,los algarrobos,8.5,-82.43,86.0,74,40,6.93,PA,1596238270
553,553,great yarmouth,52.61,1.73,73.0,82,58,1.01,GB,1596238270
554,554,kloulklubed,7.04,134.26,78.8,94,90,5.82,PW,1596238270
555,555,tabou,4.42,-7.35,75.15,86,92,11.92,CI,1596238271
556,556,sao gabriel da cachoeira,-0.13,-67.09,77.09,64,10,0.78,BR,1596238271

In [7]:
clear_data = data.drop(data.columns[[0]], axis=1)
clear_data

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,pacific grove,36.62,-121.92,71.01,60,1,9.17,US,1596238050
1,hermanus,-34.42,19.23,44.01,95,1,5.75,ZA,1596238148
2,hobyo,5.35,48.53,77.16,75,1,28.16,SO,1596238149
3,pitimbu,-7.47,-34.81,73.4,94,20,5.82,BR,1596238149
4,hobart,-42.88,147.33,50.0,71,75,10.29,AU,1596237898
...,...,...,...,...,...,...,...,...,...
552,los algarrobos,8.5,-82.43,86.0,74,40,6.93,PA,1596238270
553,great yarmouth,52.61,1.73,73.0,82,58,1.01,GB,1596238270
554,kloulklubed,7.04,134.26,78.8,94,90,5.82,PW,1596238270
555,tabou,4.42,-7.35,75.15,86,92,11.92,CI,1596238271
556,sao gabriel da cachoeira,-0.13,-67.09,77.09,64,10,0.78,BR,1596238271

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [9]:
gmaps.configure(api_key=g_key)

In [10]:
locations= clear_data[["Lat", "Lng"]].astype(float)
humidity_rate = clear_data['Humidity'].astype(float)

In [13]:
fig = gmaps.figure()
heatmap_layer = gmaps.heatmap_layer(locations, weights = humidity_rate, 
                                    dissipating=False, max_intensity=100, point_radius=1)

In [14]:
fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [28]:
ideal_weather_condition = clear_data.loc[(clear_data['Max Temp'].astype(float) <80)&
                                         (clear_data['Max Temp'].astype(float)>=70)& 
                                         (clear_data['Wind Speed'].astype(float)<10)&
                                         (clear_data['Cloudiness'].astype(float)==0),:]
ideal_weather_condition

ideal_weather_condition = ideal_weather_condition.dropna()

ideal_weather_condition

#Wind speed less than 10 mph.
#Zero cloudiness.
#Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
31,raesfeld,51.77,6.85,75.99,53,0,7.0,DE,1596238155
58,porangatu,-13.44,-49.15,74.39,21,0,7.9,BR,1596238161
137,sao felix do xingu,-6.64,-51.99,79.32,38,0,2.8,BR,1596238177
209,gat,31.61,34.76,77.0,59,0,1.01,IL,1596238192
214,canakkale,40.08,26.83,75.2,73,0,3.36,TR,1596238193
223,korla,41.76,86.15,77.0,66,0,4.0,CN,1596238194
244,katsuura,35.13,140.3,78.01,85,0,1.99,JP,1596238199
245,zhangjiakou,40.81,114.88,71.92,76,0,3.47,CN,1596238200
247,hun,29.13,15.95,77.0,43,0,4.72,LY,1596238200
266,beziers,43.35,3.22,75.99,94,0,4.7,FR,1596238206
273,san borja,-14.82,-66.85,71.29,62,0,2.53,BO,1596238207
309,mao,39.89,4.27,77.0,88,0,5.82,ES,1596238215
316,diamantino,-14.41,-56.45,78.8,29,0,3.56,BR,1596238121
368,lithakia,37.72,20.83,71.6,88,0,3.36,GR,1596238228
434,zhangye,38.93,100.45,72.68,26,0,7.27,CN,1596238243
445,gazojak,41.19,61.4,71.47,37,0,6.82,TM,1596238246
497,borogontsy,62.67,131.17,70.74,44,0,5.06,RU,1596238258

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [35]:
hotel_df = ideal_weather_condition.reset_index(drop = True)
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,raesfeld,51.77,6.85,75.99,53,0,7.0,DE,1596238155
1,porangatu,-13.44,-49.15,74.39,21,0,7.9,BR,1596238161
2,sao felix do xingu,-6.64,-51.99,79.32,38,0,2.8,BR,1596238177
3,gat,31.61,34.76,77.0,59,0,1.01,IL,1596238192
4,canakkale,40.08,26.83,75.2,73,0,3.36,TR,1596238193
5,korla,41.76,86.15,77.0,66,0,4.0,CN,1596238194
6,katsuura,35.13,140.3,78.01,85,0,1.99,JP,1596238199
7,zhangjiakou,40.81,114.88,71.92,76,0,3.47,CN,1596238200
8,hun,29.13,15.95,77.0,43,0,4.72,LY,1596238200
9,beziers,43.35,3.22,75.99,94,0,4.7,FR,1596238206
10,san borja,-14.82,-66.85,71.29,62,0,2.53,BO,1596238207
11,mao,39.89,4.27,77.0,88,0,5.82,ES,1596238215
12,diamantino,-14.41,-56.45,78.8,29,0,3.56,BR,1596238121
13,lithakia,37.72,20.83,71.6,88,0,3.36,GR,1596238228
14,zhangye,38.93,100.45,72.68,26,0,7.27,CN,1596238243
15,gazojak,41.19,61.4,71.47,37,0,6.82,TM,1596238246
16,borogontsy,62.67,131.17,70.74,44,0,5.06,RU,1596238258

In [41]:
hotel_df["Hotel Name"] = " "
hotel_df["Hotel Address"] = " "
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Address
0,raesfeld,51.77,6.85,75.99,53,0,7.0,DE,1596238155,,
1,porangatu,-13.44,-49.15,74.39,21,0,7.9,BR,1596238161,,
2,sao felix do xingu,-6.64,-51.99,79.32,38,0,2.8,BR,1596238177,,
3,gat,31.61,34.76,77.0,59,0,1.01,IL,1596238192,,
4,canakkale,40.08,26.83,75.2,73,0,3.36,TR,1596238193,,
5,korla,41.76,86.15,77.0,66,0,4.0,CN,1596238194,,
6,katsuura,35.13,140.3,78.01,85,0,1.99,JP,1596238199,,
7,zhangjiakou,40.81,114.88,71.92,76,0,3.47,CN,1596238200,,
8,hun,29.13,15.95,77.0,43,0,4.72,LY,1596238200,,
9,beziers,43.35,3.22,75.99,94,0,4.7,FR,1596238206,,
10,san borja,-14.82,-66.85,71.29,62,0,2.53,BO,1596238207,,
11,mao,39.89,4.27,77.0,88,0,5.82,ES,1596238215,,
12,diamantino,-14.41,-56.45,78.8,29,0,3.56,BR,1596238121,,
13,lithakia,37.72,20.83,71.6,88,0,3.36,GR,1596238228,,
14,zhangye,38.93,100.45,72.68,26,0,7.27,CN,1596238243,,
15,gazojak,41.19,61.4,71.47,37,0,6.82,TM,1596238246,,
16,borogontsy,62.67,131.17,70.74,44,0,5.06,RU,1596238258,,

In [56]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {
    "keyword": "hotel",
    "radius": 8000,
    "key": g_key
}

for index, row in hotel_df.iterrows():
    
    params['location'] = f"{row['Lat']}, {row['Lng']}"
    
    response = requests.get(base_url, params=params).json()
    results = response['results']
    try:
        
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        hotel_df.loc[index, "Hotel Address"] = results[0]['vicinity']
        
    except (KeyError, IndexError):
        print('Missing field')

Missing field
Missing field
Missing field

In [61]:
hotel_df = hotel_df.dropna()
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Address
0,raesfeld,51.77,6.85,75.99,53,0,7.0,DE,1596238155,Schloss Raesfeld,"Freiheit 25-27, Raesfeld"
1,porangatu,-13.44,-49.15,74.39,21,0,7.9,BR,1596238161,Lagoa Hotel Porangatu,"Av. BrasÃ­lia, 28 - Vila Primavera, Porangatu"
2,sao felix do xingu,-6.64,-51.99,79.32,38,0,2.8,BR,1596238177,Apart Hotel Rio Xingu,"Av. Rio Xingu, 2113, SÃ£o FÃ©lix do Xingu"
3,gat,31.61,34.76,77.0,59,0,1.01,IL,1596238192,Dream Island Spa & Health Resort,"Shfelat Yoav PO Box. 72, Yoav"
4,canakkale,40.08,26.83,75.2,73,0,3.36,TR,1596238193,,
5,korla,41.76,86.15,77.0,66,0,4.0,CN,1596238194,Loulan Hotel,"2 Guangchang Rd, Korla, Bayingolin Mongol Auto..."
6,katsuura,35.13,140.3,78.01,85,0,1.99,JP,1596238199,Hotel Blueberry Hill Katsuura,"1920 Okitsu, Katsuura"
7,zhangjiakou,40.81,114.88,71.92,76,0,3.47,CN,1596238200,Zhangjiakou International Hotel,"8 Changcheng W St, Qiaodong District, Zhangjia..."
8,hun,29.13,15.95,77.0,43,0,4.72,LY,1596238200,Alrwasi Hotel,houn-aljoufra
9,beziers,43.35,3.22,75.99,94,0,4.7,FR,1596238206,L'hÃ´tel Particulier BÃ©ziers - 4 Ã‰toiles - Shop...,"65 Bis Avenue 22 AoÃ»t 1944, BÃ©ziers"
10,san borja,-14.82,-66.85,71.29,62,0,2.53,BO,1596238207,La Estrella,
11,mao,39.89,4.27,77.0,88,0,5.82,ES,1596238215,Casa LÃ¡dico Boutique Hotel,"Carrer d'Anuncivay, 26, MaÃ³"
12,diamantino,-14.41,-56.45,78.8,29,0,3.56,BR,1596238121,Hotel Villa Dos parecis,Rua Suely Terezinha Dias Mendes n 482- Bairr o...
13,lithakia,37.72,20.83,71.6,88,0,3.36,GR,1596238228,Mediterranean Beach Resort,"Laganas Beach, Zakinthos"
14,zhangye,38.93,100.45,72.68,26,0,7.27,CN,1596238243,Jinyang International Hotel,"299 W Ring Rd, Ganzhou District, Zhangye"
15,gazojak,41.19,61.4,71.47,37,0,6.82,TM,1596238246,Hotel Pitnak Fayz-Baraka,Pitnak
16,borogontsy,62.67,131.17,70.74,44,0,5.06,RU,1596238258,,

In [62]:
# NOTE: Do not change any of the code in this cell
# Using the template add the hotel marks to the heatmap

info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]].astype(float)

marker_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [65]:
# Add marker layer ontop of heat map
locations = data[['Lat', 'Lng']].astype(float)
temp = data["Max Temp"].astype(float)
#setup the center of map
gmap_layer = gmaps.heatmap_layer(
                                locations, 
                                weights = temp,
                                dissipating=False,
                                max_intensity=100,
                                point_radius = 2)

# Display figure
fig.add_layer(gmap_layer)
fig

Figure(layout=FigureLayout(height='420px'))